FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# 5. Copy the rest of your application code (main.py, etc.)
COPY main.py .

# 8. The command to run the FastAPI application using Uvicorn
CMD uvicorn main:app --host 0.0.0.0 --port $PORT